


//------------------------------------------------------------------------------
// <auto-generated>
//     此代码是根据模板生成的。
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，则所做更改将丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Linq.Expressions;
using WeatherLib.Model;

namespace WeatherLib.DAL
{
    public partial class UnitOfWork : WeatherLib.Infrastructure.DAL.UnitOfWork
    {
       public WeatherLib.Model.WeatherDBContext Context { get { return context as WeatherLib.Model.WeatherDBContext; } }
       public UnitOfWork(WeatherLib.Model.WeatherDBContext context) : base(context)
       {
       }
       
       
       public UnitOfWork() : this(WeatherLib.Model.WeatherDBContext.CurrentHttpContext){
        
       }
       
       public int? ContextCommandTimeOut {
         get {
            return Context.GetCommandTimeout();
          }
          set {
            Context.SetCommandTimeout(value);
          }
        }
    	
    
      private BaseEmployeeRepository _BaseEmployeeRepository = null;
      public BaseEmployeeRepository BaseEmployeeRepository {
        get
    	{
    	  if (_BaseEmployeeRepository == null)
    	  {
    	    _BaseEmployeeRepository = new BaseEmployeeRepository(this);
    	  }
    	  return _BaseEmployeeRepository;
    	}
      }
      
    
      private BaseUserRepository _BaseUserRepository = null;
      public BaseUserRepository BaseUserRepository {
        get
    	{
    	  if (_BaseUserRepository == null)
    	  {
    	    _BaseUserRepository = new BaseUserRepository(this);
    	  }
    	  return _BaseUserRepository;
    	}
      }
      
    
      private BASE_ROLERepository _BASE_ROLERepository = null;
      public BASE_ROLERepository BASE_ROLERepository {
        get
    	{
    	  if (_BASE_ROLERepository == null)
    	  {
    	    _BASE_ROLERepository = new BASE_ROLERepository(this);
    	  }
    	  return _BASE_ROLERepository;
    	}
      }
      
    
      private BASE_USER_ROLERepository _BASE_USER_ROLERepository = null;
      public BASE_USER_ROLERepository BASE_USER_ROLERepository {
        get
    	{
    	  if (_BASE_USER_ROLERepository == null)
    	  {
    	    _BASE_USER_ROLERepository = new BASE_USER_ROLERepository(this);
    	  }
    	  return _BASE_USER_ROLERepository;
    	}
      }
      
    
      private JD_ProductRepository _JD_ProductRepository = null;
      public JD_ProductRepository JD_ProductRepository {
        get
    	{
    	  if (_JD_ProductRepository == null)
    	  {
    	    _JD_ProductRepository = new JD_ProductRepository(this);
    	  }
    	  return _JD_ProductRepository;
    	}
      }
      
    
    }
}
