//------------------------------------------------------------------------------
// <auto-generated>
//     此代码是根据模板生成的。
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，则所做更改将丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Linq.Expressions;
using WeatherLib.Model;
using WeatherLib.DAL;
using WeatherLib.Utility;

namespace WeatherLib.BLL
{
    
    public partial interface IBASE_USER_ROLEBL: WeatherLib.Infrastructure.BLL.IGenericBL<BASE_USER_ROLE>
    {
      }
    
    public partial class BASE_USER_ROLEBL:
       WeatherLib.Infrastructure.BLL.GenericBL<BASE_USER_ROLE>,
       IBASE_USER_ROLEBL
    {
      public BASE_USER_ROLEBL() : base() {
        unitOfWork = new WeatherLib.DAL.UnitOfWork();
    	OnCreate();
      }
      public BASE_USER_ROLEBL(WeatherLib.DAL.UnitOfWork unitOfWork) : base() {
        this.unitOfWork = unitOfWork;
    	OnCreate();
      }
      partial void OnCreate();
      private WeatherLib.DAL.UnitOfWork UnitOfWork {
        get { return unitOfWork as WeatherLib.DAL.UnitOfWork;}
    	set { unitOfWork = value;}
      }
      private IBASE_USER_ROLERepository _repository;
      private IBASE_USER_ROLERepository Repository
      {
      	get
    	{
    	  if (_repository == null)
    	  {
    	    _repository = unitOfWork.Repository<BASE_USER_ROLE>() as IBASE_USER_ROLERepository;
    	  }
    	  return _repository;
    	}
    	set
    	{
    	  _repository = value;
    	  }
      }
        
        public override BASE_USER_ROLE InsertOrUpdate(BASE_USER_ROLE entity) {
          throw new NotImplementedException();
          }
    
    }
}
