//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeatherLib.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaseUser
    {
        public BaseUser()
        {
            this.BASE_USER_ROLE = new HashSet<BASE_USER_ROLE>();
        }
    
        public decimal ID { get; set; }
        public string UserAccount { get; set; }
        public string UserPWD { get; set; }
        public string State { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public Nullable<decimal> UpdateID { get; set; }
        public Nullable<decimal> Emp_ID { get; set; }
    
        public virtual BaseEmployee BASE_EMPLOYEE { get; set; }
        public virtual ICollection<BASE_USER_ROLE> BASE_USER_ROLE { get; set; }
    }
}
