//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeatherLib.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BASE_ROLE
    {
        public BASE_ROLE()
        {
            this.BASE_USER_ROLE = new HashSet<BASE_USER_ROLE>();
        }
    
        public decimal ID { get; set; }
        public Nullable<decimal> DATA_AUTH_ID { get; set; }
        public string ROLE_NAME { get; set; }
        public string ALLOW_DEL { get; set; }
        public string DEFAULT_ROLE { get; set; }
        public string REMARK { get; set; }
        public string STATE { get; set; }
        public Nullable<decimal> SORT { get; set; }
    
        public virtual ICollection<BASE_USER_ROLE> BASE_USER_ROLE { get; set; }
    }
}
