//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeatherLib.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BASE_USER_ROLE
    {
        public decimal ID { get; set; }
        public Nullable<decimal> USER_ID { get; set; }
        public Nullable<decimal> ROLE_ID { get; set; }
    
        public virtual BASE_ROLE BASE_ROLE { get; set; }
        public virtual BaseUser BASE_USER { get; set; }
    }
}
