//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeatherLib.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeatherCity
    {
        public decimal ID { get; set; }
        public string CityCode { get; set; }
        public string NameEN { get; set; }
        public string Name_CN { get; set; }
        public string CountryCode { get; set; }
        public string CountryEN { get; set; }
        public string CountryCN { get; set; }
        public string ProvinceEN { get; set; }
        public string ProvinceCN { get; set; }
        public Nullable<decimal> ParentID { get; set; }
        public string ParentEN { get; set; }
        public string ParentCN { get; set; }
        public string Longitude { get; set; }
        public string Latitude { get; set; }
        public string State { get; set; }
        public string Level { get; set; }
    }
}
