//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeatherLib.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeatherDailyForecast
    {
        public decimal ID { get; set; }
        public string AstroMR { get; set; }
        public string AstroMS { get; set; }
        public string AstroSR { get; set; }
        public string AstroSS { get; set; }
        public string CondCodeD { get; set; }
        public string CondCodeN { get; set; }
        public string CondTxtD { get; set; }
        public string CondTxtN { get; set; }
        public string Date { get; set; }
        public Nullable<double> Hum { get; set; }
        public Nullable<double> Pcpn { get; set; }
        public Nullable<double> Pop { get; set; }
        public Nullable<double> Pres { get; set; }
        public Nullable<double> TmpMax { get; set; }
        public Nullable<double> TmpMin { get; set; }
        public Nullable<double> Vis { get; set; }
        public Nullable<double> WindDeg { get; set; }
        public string WindDir { get; set; }
        public string WindSC { get; set; }
        public Nullable<double> WindSpd { get; set; }
        public string CityName { get; set; }
        public string CityCode { get; set; }
        public string State { get; set; }
    }
}
