USE [ManagerSi]
GO

/****** Object:  Table [dbo].[BASE_USER]    Script Date: 2017/4/22 22:48:15 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[BASE_USER](
	[ID] [decimal](18, 0) IDENTITY(1,1) NOT NULL,
	[UserAccount] [nvarchar](20) NOT NULL,
	[UserPWD] [nvarchar](20) NULL,
	[State] [char](1) NULL,
	[UpdateTime] [datetime] NULL,
	[UpdateID] [decimal](18, 0) NULL,
	[Emp_ID] [decimal](18, 0) NULL,
 CONSTRAINT [PK_BASE_USER] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[BASE_USER]  WITH CHECK ADD  CONSTRAINT [FK_BASE_USER_BASE_EMPLOYEE] FOREIGN KEY([Emp_ID])
REFERENCES [dbo].[BASE_EMPLOYEE] ([ID])
GO

ALTER TABLE [dbo].[BASE_USER] CHECK CONSTRAINT [FK_BASE_USER_BASE_EMPLOYEE]
GO


